// Copyright 2023 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        XXXXXXX, XXXXXXX, XXXXXXX,   XXXXXXX, XXXXXXX, KC_HELP,   XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX,
        XXXXXXX, KC_MSEL, XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX,   KC_DEL,
        XXXXXXX, XXXXXXX, XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX,   KC_COPY,
        XXXXXXX, KC_DEL,  XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, KC_PAUS, XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX,   XXXXXXX,
        XXXXXXX, KC_ESC,    KC_7,    KC_8,    KC_9,    KC_PLUS,   XXXXXXX, XXXXXXX, XXXXXXX,
        KC_4,    KC_5,      KC_6,    XXXXXXX, XXXXXXX, XXXXXXX,
        KC_1,    KC_2,      KC_3,    KC_MINS, KC_UP,   XXXXXXX,            XXXXXXX,                   KC_CLR,
                            KC_0,    KC_DOT,  XXXXXXX, XXXXXXX,   KC_MPRV, XXXXXXX, KC_MNXT,          XXXXXXX,
        XXXXXXX,            XXXXXXX,                   XXXXXXX,            KC_DOWN,                   XXXXXXX,

        KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,     KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,    XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,   KC_PGUP
    )
};
